version: '2'
services:
    todolist-app:
        image: todolist
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todolist-postgresql:5432/todolist
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    todolist-postgresql:
        extends:
            file: postgresql.yml
            service: todolist-postgresql
