version: '2'
services:
    todolist-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/todolist/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=todolist
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
